AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS SAM template for algorithm/production rule EPG
#Author: Hieu Phung @SOLERS INC (hieu.phung@solers.com)
Globals:
  Function:
    VpcConfig:
      SecurityGroupIds:
        - sg-1e601b69
      SubnetIds:
        - subnet-49c98914
        - subnet-faafe3d5
        - subnet-d0054bef
        - subnet-6f3d2924
    # Environment:
    #   Variables:
    #     ES_HOST: 'https://vpc-nde-test-sncp4dqd63lf4rs2vdihlk763e.us-east-1.es.amazonaws.com'
    #     ES_PORT: '443'
    #     RD_HOST: 'ndedev2.cixifosqwtgg.us-east-1.rds.amazonaws.com'
    #     RD_DBNM: 'nde_dev2'
    #     RD_USER: 'nde_dev2'
    #     RD_PSWD: 'nde'
    #     RD_HOST: 'nde-pgsql.cixifosqwtgg.us-east-1.rds.amazonaws.com'
    #     RD_DBNM: 'nde_dev1'
    #     RD_USER: 'nde_dev1'
    #     RD_PSWD: 'nde'
Resources:
  registerAlgorithm:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_functions/registerAlgorithm.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::784330347242:role/service-role/MyRole'
      CodeUri: .debug/
      Environment:
        Variables:
          ES_HOST: 'https://vpc-nde-test-sncp4dqd63lf4rs2vdihlk763e.us-east-1.es.amazonaws.com'
          ES_PORT: '443'
          # RD_HOST: 'ndedev2.cixifosqwtgg.us-east-1.rds.amazonaws.com'
          # RD_DBNM: 'nde_dev2'
          # RD_USER: 'nde_dev2'
          # RD_PSWD: 'nde'
          RD_HOST: 'nde-pgsql.cixifosqwtgg.us-east-1.rds.amazonaws.com'
          RD_DBNM: 'nde_dev1'
          RD_USER: 'nde_dev1'
          RD_PSWD: 'nde'
  getAlgorithm:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_functions/getAlgorithm.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::784330347242:role/service-role/MyRole'
      CodeUri: .debug/
      Environment:
        Variables:
          ES_HOST: 'https://vpc-nde-test-sncp4dqd63lf4rs2vdihlk763e.us-east-1.es.amazonaws.com'
          ES_PORT: '443'
          # RD_HOST: 'ndedev2.cixifosqwtgg.us-east-1.rds.amazonaws.com'
          # RD_DBNM: 'nde_dev2'
          # RD_USER: 'nde_dev2'
          # RD_PSWD: 'nde'
          RD_HOST: 'nde-pgsql.cixifosqwtgg.us-east-1.rds.amazonaws.com'
          RD_DBNM: 'nde_dev1'
          RD_USER: 'nde_dev1'
          RD_PSWD: 'nde'
  getAlgorithmList:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_functions/getAlgorithmList.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::784330347242:role/service-role/MyRole'
      CodeUri: .debug/
      Environment:
        Variables:
          ES_HOST: 'https://vpc-nde-test-sncp4dqd63lf4rs2vdihlk763e.us-east-1.es.amazonaws.com'
          ES_PORT: '443'
          # RD_HOST: 'ndedev2.cixifosqwtgg.us-east-1.rds.amazonaws.com'
          # RD_DBNM: 'nde_dev2'
          # RD_USER: 'nde_dev2'
          # RD_PSWD: 'nde'
          RD_HOST: 'nde-pgsql.cixifosqwtgg.us-east-1.rds.amazonaws.com'
          RD_DBNM: 'nde_dev1'
          RD_USER: 'nde_dev1'
          RD_PSWD: 'nde'
  registerProductionRule:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_functions/registerProductionRule.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::784330347242:role/service-role/MyRole'
      CodeUri: .debug/
      Environment:
        Variables:
          NDEMODE: 'NDE_DEV1'
          SANPATH: '/mnt/NAS/nde'
          ES_HOST: 'https://vpc-nde-test-sncp4dqd63lf4rs2vdihlk763e.us-east-1.es.amazonaws.com'
          ES_PORT: '443'
          # RD_HOST: 'ndedev2.cixifosqwtgg.us-east-1.rds.amazonaws.com'
          # RD_DBNM: 'nde_dev2'
          # RD_USER: 'nde_dev2'
          # RD_PSWD: 'nde'
          RD_HOST: 'nde-pgsql.cixifosqwtgg.us-east-1.rds.amazonaws.com'
          RD_DBNM: 'nde_dev1'
          RD_USER: 'nde_dev1'
          RD_PSWD: 'nde'
  getProductionRule:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_functions/getProductionRule.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::784330347242:role/service-role/MyRole'
      CodeUri: .debug/
      Environment:
        Variables:
          ES_HOST: 'https://vpc-nde-test-sncp4dqd63lf4rs2vdihlk763e.us-east-1.es.amazonaws.com'
          ES_PORT: '443'
          # RD_HOST: 'ndedev2.cixifosqwtgg.us-east-1.rds.amazonaws.com'
          # RD_DBNM: 'nde_dev2'
          # RD_USER: 'nde_dev2'
          # RD_PSWD: 'nde'
          RD_HOST: 'nde-pgsql.cixifosqwtgg.us-east-1.rds.amazonaws.com'
          RD_DBNM: 'nde_dev1'
          RD_USER: 'nde_dev1'
          RD_PSWD: 'nde'
  getProductionRuleList:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_functions/getProductionRuleList.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::784330347242:role/service-role/MyRole'
      CodeUri: .debug/
      Environment:
        Variables:
          ES_HOST: 'https://vpc-nde-test-sncp4dqd63lf4rs2vdihlk763e.us-east-1.es.amazonaws.com'
          ES_PORT: '443'
          # RD_HOST: 'ndedev2.cixifosqwtgg.us-east-1.rds.amazonaws.com'
          # RD_DBNM: 'nde_dev2'
          # RD_USER: 'nde_dev2'
          # RD_PSWD: 'nde'
          RD_HOST: 'nde-pgsql.cixifosqwtgg.us-east-1.rds.amazonaws.com'
          RD_DBNM: 'nde_dev1'
          RD_USER: 'nde_dev1'
          RD_PSWD: 'nde'
  toggleProductionRule:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_functions/toggleProductionRule.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::784330347242:role/service-role/MyRole'
      CodeUri: .debug/
      Environment:
        Variables:
          # RD_HOST: 'ndedev2.cixifosqwtgg.us-east-1.rds.amazonaws.com'
          # RD_DBNM: 'nde_dev2'
          # RD_USER: 'nde_dev2'
          # RD_PSWD: 'nde'
          RD_HOST: 'nde-pgsql.cixifosqwtgg.us-east-1.rds.amazonaws.com'
          RD_DBNM: 'nde_dev1'
          RD_USER: 'nde_dev1'
          RD_PSWD: 'nde'