AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS SAM template for factory EPG
#Author: Hieu Phung; SOLERS INC (hieu.phung@solers.com)
Globals:
  Function:
    VpcConfig:
      SecurityGroupIds:
        - sg-1e601b69
      SubnetIds:
        - subnet-49c98914
        - subnet-faafe3d5
        - subnet-d0054bef
        - subnet-6f3d2924
Resources:
  processTrigger:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_functions/processTrigger.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::784330347242:role/service-role/readS3Role'
      CodeUri: .debug/
      Environment:
        Variables:
          # ES_HOST: 'https://vpc-nde-dev2-jnk45bdfrsochphfpjinhf6dxu.us-east-1.es.amazonaws.com'
          # ES_PORT: '443'
          # RD_HOST: 'ndedev2.cixifosqwtgg.us-east-1.rds.amazonaws.com'
          # RD_DBNM: 'nde_dev2'
          # RD_USER: 'nde_dev2'
          # RD_PSWD: 'nde'
          RD_HOST: 'nde-pgsql.cixifosqwtgg.us-east-1.rds.amazonaws.com'
          RD_DBNM: 'nde_dev1'
          RD_USER: 'nde_dev1'
          RD_PSWD: 'nde'
  jobSpecPoller:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_functions/jobSpecPoller.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::784330347242:role/service-role/readS3Role'
      CodeUri: .debug/
      Environment:
        Variables:
          # ES_HOST: 'https://vpc-nde-dev2-jnk45bdfrsochphfpjinhf6dxu.us-east-1.es.amazonaws.com'
          # ES_PORT: '443'
          # RD_HOST: 'ndedev2.cixifosqwtgg.us-east-1.rds.amazonaws.com'
          # RD_DBNM: 'nde_dev2'
          # RD_USER: 'nde_dev2'
          # RD_PSWD: 'nde'
          RD_HOST: 'nde-pgsql.cixifosqwtgg.us-east-1.rds.amazonaws.com'
          RD_DBNM: 'nde_dev1'
          RD_USER: 'nde_dev1'
          RD_PSWD: 'nde'
  completeJobSpec:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_functions/completeJobSpec.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::784330347242:role/service-role/readS3Role'
      CodeUri: .debug/
      Environment:
        Variables:
          # ES_HOST: 'https://vpc-nde-dev2-jnk45bdfrsochphfpjinhf6dxu.us-east-1.es.amazonaws.com'
          # ES_PORT: '443'
          # RD_HOST: 'ndedev2.cixifosqwtgg.us-east-1.rds.amazonaws.com'
          # RD_DBNM: 'nde_dev2'
          # RD_USER: 'nde_dev2'
          # RD_PSWD: 'nde'
          RD_HOST: 'nde-pgsql.cixifosqwtgg.us-east-1.rds.amazonaws.com'
          RD_DBNM: 'nde_dev1'
          RD_USER: 'nde_dev1'
          RD_PSWD: 'nde'
