nohup python3 ingestNdeRest.py &
nohup python3 ingestNdeRest.py &
nohup python3 ingestNdeRest.py &
nohup python3 ingestNdeRest.py &
nohup python3 ingestNdeRest.py &
nohup python3 ingestNdeRest.py &
nohup python3 ingestNdeRest.py &
nohup python3 ingestNdeRest.py &
nohup python3 ingestNdeRest.py &
nohup python3 ingestNdeRest.py &
nohup python3 ingestNdeRest.py &
nohup python3 ingestNdeRest.py &
nohup python3 ingestGoesRest.py &