AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
#Author: Hieu Phung @SOLERS INC (hieu.phung@solers.com)
Globals:
  Function:
    VpcConfig:
      SecurityGroupIds:
        - sg-1e601b69
      SubnetIds:
        - subnet-49c98914
        - subnet-faafe3d5
        - subnet-d0054bef
        - subnet-6f3d2924
Resources:
  jwtAuth:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_functions/jwtAuth.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::784330347242:role/service-role/MyRole'
      CodeUri: .debug/
      Environment:
        Variables:
          RD_HOST: 'nde-pgsql.cixifosqwtgg.us-east-1.rds.amazonaws.com'
          RD_DBNM: 'nde_dev1'
          RD_USER: 'nde_dev1'
          RD_PSWD: 'nde'
          SCRTKEY: 'two_weeks'
